# Generated by Django 6.0.3 on 2026-03-19 03:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recordings', '0002_alter_recording_normalized_file_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilenceSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.BigIntegerField()),
                ('end_time', models.BigIntegerField()),
                ('model_used', models.CharField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recording_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silence_segments', to='recordings.recording')),
            ],
            options={
                'ordering': ['recording_id', 'start_time', 'end_time'],
                'indexes': [models.Index(fields=['recording_id', 'start_time'], name='silence_seg_rec_start_idx'), models.Index(fields=['recording_id', 'end_time'], name='silence_seg_recording_end_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='silence_segment_end_gt_start')],
            },
        ),
        migrations.CreateModel(
            name='SpeakerLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker_id', models.CharField(max_length=128)),
                ('display_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_labels', to='recordings.recording')),
            ],
            options={
                'ordering': ['recording_id', 'speaker_id'],
                'indexes': [models.Index(fields=['recording_id', 'speaker_id'], name='speaker_label_rec_speaker_idx')],
                'constraints': [models.UniqueConstraint(fields=('recording_id', 'speaker_id'), name='unique_speaker_label_per_recording_id')],
            },
        ),
        migrations.CreateModel(
            name='SpeakerSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker_id', models.CharField(max_length=128)),
                ('start_time', models.BigIntegerField()),
                ('end_time', models.BigIntegerField()),
                ('model_used', models.CharField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recording_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_segments', to='recordings.recording')),
            ],
            options={
                'ordering': ['recording_id', 'start_time', 'end_time'],
                'indexes': [models.Index(fields=['recording_id', 'speaker_id'], name='speaker_seg_rec_speaker_idx'), models.Index(fields=['recording_id', 'start_time'], name='speaker_seg_rec_start_idx'), models.Index(fields=['recording_id', 'end_time'], name='speaker_seg_recording_end_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='speaker_segment_end_gt_start')],
            },
        ),
    ]
