# Generated by Django 6.0.3 on 2026-03-19 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='silencesegment',
            old_name='recording_id',
            new_name='recording',
        ),
        migrations.RenameField(
            model_name='speakerlabel',
            old_name='recording_id',
            new_name='recording',
        ),
        migrations.RenameField(
            model_name='speakersegment',
            old_name='recording_id',
            new_name='recording',
        ),
    ]
