# Generated by Django 6.0.3 on 2026-03-18 02:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file_name', models.CharField(max_length=512)),
                ('original_file_path', models.TextField()),
                ('normalized_file_path', models.TextField(blank=True)),
                ('duration_milliseconds', models.BigIntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('normalized', 'Normalized'), ('diarized', 'Diarized'), ('transcribing', 'Transcribing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('start_time', models.BigIntegerField()),
                ('end_time', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_review', 'Needs Review')], default='pending', max_length=32)),
                ('worker_id', models.CharField(blank=True, max_length=128, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_requested_model', models.CharField(blank=True, max_length=64, null=True)),
                ('has_pending_candidate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='recordings.recording')),
            ],
            options={
                'ordering': ['-created_at', 'chunk_index'],
                'indexes': [models.Index(fields=['recording', 'chunk_index'], name='chunk_rec_idx_idx'), models.Index(fields=['status'], name='chunk_status_idx'), models.Index(fields=['worker_id'], name='chunk_worker_idx'), models.Index(fields=['heartbeat_at'], name='chunk_heartbeat_idx')],
                'constraints': [models.UniqueConstraint(fields=('recording', 'chunk_index'), name='unique_chunk_index_per_recording'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='chunk_end_gt_start')],
            },
        ),
    ]
