# Generated by Django 6.0.3 on 2026-03-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='normalized_file_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='recording',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('normalized_file_path__isnull', True), ('status', 'uploaded')), ('normalized_file_path__isnull', False), _connector='OR'), name='normalized_audio_state_consistency'),
        ),
    ]
