# Generated by Django 6.0.3 on 2026-03-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_alter_recording_normalized_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('normalized', 'Normalized'), ('diarized', 'Diarized'), ('chunked', 'Chunked'), ('transcribing', 'Transcribing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=32),
        ),
    ]
