import uuid

from django.db import models
from django.utils import timezone

from recordings.models import Recording


class SpeakerSegment(models.Model):
    """
    Time range within a recording assigned to a speaker by diarization.

    Speaker segments are generated from full-recording diarization and represent the canonical speaker timeline
    for a recording.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    recording = models.ForeignKey(Recording, on_delete=models.CASCADE, related_name='speaker_segments')
    speaker_id = models.CharField(max_length=128)
    start_time = models.BigIntegerField()
    end_time = models.BigIntegerField()
    model_used = models.CharField()
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["recording_id","start_time","end_time"]
        constraints = [
            models.CheckConstraint(
                condition=models.Q(end_time__gt=models.F('start_time')),
                name='speaker_segment_end_gt_start',
            ),
        ]
        indexes = [
            models.Index(
                fields=['recording_id','speaker_id'],
                name='speaker_seg_rec_speaker_idx',
            ),
            models.Index(
                fields=['recording_id','start_time'],
                name='speaker_seg_rec_start_idx',
            ),
            models.Index(
                fields=['recording_id','end_time'],
                name='speaker_seg_recording_end_idx',
            ),
        ]

    def __str__(self) -> str:
        return f"{self.recording_id}:{self.speaker_id} [{self.start_time}-{self.end_time}]"

    @property
    def duration_milliseconds(self) -> int:
        return self.end_time -self.start_time


class SilenceSegment(models.Model):
    """
    Silence interval detected in a recording.

    Silence segments are generated by VAD and can later be used for pause annotations, pacing analysis, or optional
    rendering in the editor.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    recording = models.ForeignKey(Recording, on_delete=models.CASCADE, related_name='silence_segments')
    start_time = models.BigIntegerField()
    end_time = models.BigIntegerField()
    model_used = models.CharField()
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ["recording_id","start_time","end_time"]
        constraints = [
            models.CheckConstraint(
                condition=models.Q(end_time__gt=models.F('start_time')),
                name='silence_segment_end_gt_start',
            ),
        ]
        indexes = [
            models.Index(
                fields=['recording_id','start_time'],
                name='silence_seg_rec_start_idx',
            ),
            models.Index(
                fields=['recording_id','end_time'],
                name='silence_seg_recording_end_idx',
            )
        ]

    def __str__(self) -> str:
        return f"{self.recording_id}:silence [{self.start_time}- {self.end_time}]"

    @property
    def duration_milliseconds(self) -> int:
        return self.end_time - self.start_time


class SpeakerLabel(models.Model):
    """
    User-defined display label for a speaker within a recording.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    recording = models.ForeignKey(Recording, on_delete=models.CASCADE, related_name='speaker_labels')
    speaker_id = models.CharField(max_length=128)
    display_name = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["recording_id","speaker_id"]
        constraints = [
            models.UniqueConstraint(
                fields=['recording_id','speaker_id'],
                name='unique_speaker_label_per_recording_id',
            ),
        ]
        indexes = [
            models.Index(
                fields=['recording_id','speaker_id'],
                name='speaker_label_rec_speaker_idx',
            ),
        ]

    def __str__(self) -> str:
        return f"{self.recording_id}:{self.speaker_id} -> {self.display_name}"