# Generated by Django 6.0.3 on 2026-03-21 14:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recordings', '0003_alter_recording_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_text', models.TextField()),
                ('model_used', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='recordings.chunk')),
            ],
            options={
                'ordering': ['chunk_id'],
            },
        ),
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edited_text', models.TextField()),
                ('editor', models.CharField(default='user', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='transcriptions.transcript')),
            ],
            options={
                'ordering': ['transcript_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_text', models.TextField()),
                ('model_used', models.CharField(max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_from_retry', models.BooleanField(default=True)),
                ('accepted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_candidates', to='recordings.chunk')),
            ],
            options={
                'ordering': ['chunk_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('start_time', models.BigIntegerField()),
                ('end_time', models.BigIntegerField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_words', to='recordings.chunk')),
            ],
            options={
                'ordering': ['chunk_id', 'word_index'],
            },
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['chunk_id'], name='transcript_chunk_idx'),
        ),
        migrations.AddIndex(
            model_name='edit',
            index=models.Index(fields=['transcript_id', 'created_at'], name='edit_transcript_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptcandidate',
            index=models.Index(fields=['chunk_id', 'created_at'], name='candidate_chunk_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptcandidate',
            index=models.Index(fields=['chunk_id', 'accepted'], name='candidate_chunk_accepted_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptword',
            index=models.Index(fields=['chunk', 'word_index'], name='transcript_word_chunk_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptword',
            index=models.Index(fields=['chunk', 'start_time'], name='transcript_word_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcriptword',
            constraint=models.UniqueConstraint(fields=('chunk_id', 'word_index'), name='unique_word_index_per_chunk'),
        ),
        migrations.AddConstraint(
            model_name='transcriptword',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='transcript_word_end_gt_start'),
        ),
    ]
