# Generated by Django 6.0.3 on 2026-03-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionRuntimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_enforcer', models.BooleanField(default=True, editable=False, help_text='Enforce a single RuntimeSettings row.', unique=True)),
                ('supervisor_enabled', models.BooleanField(default=True, help_text='Whether the worker supervisor should actively maintain workers.')),
                ('desired_worker_count', models.PositiveIntegerField(default=2, help_text='Target number of transcription workers the supervisor should try to maintain.')),
                ('max_worker_count', models.PositiveIntegerField(default=4, help_text='Hard cap for transcription workers, even if desired_worker_count is higher.')),
                ('max_job_per_worker', models.PositiveIntegerField(default=3, help_text='Recycle a worker process after this many jobs.')),
                ('max_idle_seconds', models.PositiveIntegerField(default=300, help_text='Recycle a worker if it stays idle for this many seconds.')),
                ('supervisor_poll_seconds', models.PositiveIntegerField(default=5, help_text='How often the supervisor reconciles desired vs actual workers.')),
                ('guarded_scaling_enabled', models.BooleanField(default=True, help_text='Whether the supervisor should block scale-up when machine resources are too tight.')),
                ('max_memory_percent', models.PositiveIntegerField(default=85, help_text='Block worker scale-up when system memory usage is above this percentage.')),
                ('min_available_memory_mb', models.PositiveIntegerField(default=12000, help_text='Minimum free memory required to allow spawning a new worker.')),
                ('estimated_memory_per_worker_mb', models.PositiveIntegerField(default=12000, help_text='Estimated memory per worker.')),
                ('cpu_guard_enabled', models.BooleanField(default=False, help_text='Whether CPU thresholds should participate in guarded scaling decisions.')),
                ('max_cpu_percent', models.PositiveIntegerField(default=85, help_text='If cpu_guard_enabled is true, block scale-up when CPU usage is above this percentage.')),
                ('default_backend', models.CharField(blank=True, choices=[('mlx-whisper', 'MLX_WHISPER'), ('whisper.cpp', 'WHISPER_CPP')], max_length=128, null=True)),
                ('default_model', models.CharField(blank=True, choices=[('small', 'SMALL'), ('medium', 'MEDIUM'), ('large-v3', 'LARGE_V3')], max_length=128, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transcription Runtime Settings',
                'verbose_name_plural': 'Transcription Runtime Settings',
            },
        ),
    ]
