# Generated by Django 6.0.3 on 2026-03-26 02:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0002_create_transcription_runtime_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProcessState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(help_text='Stable logical worker identifier assigned by the supervisor.', max_length=128, unique=True)),
                ('role', models.CharField(choices=[('transcription', 'Transcription'), ('diarization', 'Diarization')], default='transcription', help_text='Worker role handled by this process.')),
                ('pid', models.PositiveIntegerField(help_text='Operating system process ID.', unique=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('idle', 'Idle'), ('busy', 'Busy'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='starting', help_text='Current lifecycle status of the worker process.')),
                ('backend', models.CharField(blank=True, choices=[('mlx-whisper', 'MLX_WHISPER'), ('whisper.cpp', 'WHISPER_CPP')], help_text='Backend loaded by this worker, when applicable.', null=True)),
                ('model', models.CharField(blank=True, choices=[('small', 'SMALL'), ('medium', 'MEDIUM'), ('large-v3', 'LARGE_V3')], help_text='Model loaded by this worker, when applicable.', null=True)),
                ('current_chunk_id', models.UUIDField(blank=True, help_text='Chunk currently being processed by this worker, if any.', null=True)),
                ('jobs_processed', models.PositiveIntegerField(default=0, help_text='Number of jobs completed by this worker process.')),
                ('exit_reason', models.CharField(blank=True, default='', help_text='Reason recorded when the worker exits of is recycled.', max_length=255)),
                ('last_error', models.TextField(blank=True, default='', help_text='Most recent error observed for this worker.')),
                ('hostname', models.CharField(blank=True, default='', help_text='Host machine name running this worker.', max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when this worker started.')),
                ('last_heartbeat_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time last heartbeat reported by this worker.')),
                ('stopped_at', models.DateTimeField(blank=True, help_text='Date and time when this worker stopped, if applicable.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Worker Process State',
                'verbose_name_plural': 'Worker Process States',
            },
        ),
    ]
