# Generated by Django 6.0.3 on 2026-03-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0003_workerprocessstate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workerprocessstate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('current_chunk_id__isnull', False), ('status', 'busy')), models.Q(models.Q(('status', 'busy'), _negated=True), ('current_chunk_id__isnull', True)), _connector='OR'), name='busy_chunk_bidirectional'),
        ),
    ]
