# Generated by Django 6.0.3 on 2026-03-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0004_workerprocessstate_busy_chunk_bidirectional'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprocessstate',
            name='idle_since',
            field=models.DateTimeField(blank=True, help_text='Date and time when this worker most recently entered the idle state.', null=True),
        ),
    ]
